version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - julia-app

  julia-app:
    build: .
    image: gcr.io/probker-cloud-run/julia-app:1.0
    expose:
      - "8081"
    volumes:
      - .:/app
